apiVersion: v1
kind: Namespace
metadata:
  name: c2c-opsera-kumar-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-opsera-kumar-deployment
  namespace: c2c-opsera-kumar-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:d4072e8037e92410aa12ac84ca387e17da97d260

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-opsera-kumar-label
  name: c2c-opsera-kumar-service
  namespace: c2c-opsera-kumar-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---